services:
    admin.baseconfig:
        class: App\Admin\BaseConfigAdmin
        arguments: [~ , App\Entity\BaseConfig, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.baseConfig.title }
        public: true

    admin.baseimage:
        class: App\Admin\BaseImageAdmin
        arguments: [~ , App\Entity\BaseImage , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.baseimage.title, show_in_dashboard: false }
        public: true