services:
    admin.baseconfig:
        class: App\Admin\BaseConfigAdmin
        arguments: [~ , App\Entity\BaseConfig, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.baseConfig.title }
        public: true

    admin.baseimage:
        class: App\Admin\BaseImageAdmin
        arguments: [~ , App\Entity\BaseImage , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.baseimage.title, show_in_dashboard: false }
        public: true

    admin.baseemail:
        class: App\Admin\BaseEmailsAdmin
        arguments: [~ , App\Entity\BaseEmail , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.baseemails.title, show_in_dashboard: false }
        public: true

    admin.basephones:
        class: App\Admin\BasePhonesAdmin
        arguments: [~ , App\Entity\BasePhones , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.basephones.title, show_in_dashboard: false }
        public: true

    admin.basesocial:
        class: App\Admin\BaseSocialAdmin
        arguments: [~ , App\Entity\BaseSocial , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.basesocial.title, show_in_dashboard: false }
        public: true

    admin.basepartner:
        class: App\Admin\BasePartnerAdmin
        arguments: [~ , App\Entity\BasePartners , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.basepartner.title, show_in_dashboard: false }
        public: true

    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~ , App\Entity\Category , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.category.title, show_in_dashboard: true }
        public: true

    admin.groupproduct:
        class: App\Admin\GroupProductAdmin
        arguments: [~ , App\Entity\GroupProduct , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.groupproduct.title, show_in_dashboard: true }
        public: true

    admin.products:
        class: App\Admin\ProductAdmin
        arguments: [~ , App\Entity\Product , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.product.title, show_in_dashboard: true }
        public: true

    admin.productimage:
        class: App\Admin\ProductImageAdmin
        arguments: [~ , App\Entity\ProductImage , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.productimage.title, show_in_dashboard: false }
        public: true

    admin.stock:
        class: App\Admin\StockAdmin
        arguments: [~ , App\Entity\Stock , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.stock.title, show_in_dashboard: true }
        public: true

    admin.order:
        class: App\Admin\OrdersAdmin
        arguments: [~ , App\Entity\Order , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.orders.title }
        calls:
            - [setTemplate, ['outer_list_rows_list' ,'admin/Order/row.html.twig' ]]
        public: true

    admin.order_items:
        class: App\Admin\OrdersItemsAdmin
        arguments: [~ , App\Entity\OrderItem , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.order_item.title, show_in_dashboard: false }
        public: true

    admin.product_characteristic:
        class: App\Admin\ProductCharacteristicAdmin
        arguments: [~ , App\Entity\ProductCharacteristic , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.product_haracteristic.title, show_in_dashboard: true }
        public: true

    admin.characteristic_value:
        class: App\Admin\CharacteristicValueAdmin
        arguments: [~ , App\Entity\CharacteristicValue , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.characteristic_calue.title, show_in_dashboard: true }
        public: true

    admin.characteristic_item_for_category:
        class: App\Admin\CharacteristicItemForCategoryAdmin
        arguments: [~ , App\Entity\CharacteristicItemForCategory , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.characteristic_item_for_category.title, show_in_dashboard: false }
        public: true

    admin.characteristic_item_for_product:
        class: App\Admin\CharacteristicItemForProductAdmin
        arguments: [~ , App\Entity\CharacteristicItemForProduct , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.characteristic_item_for_category.product, show_in_dashboard: false }
        public: true

    admin.question:
        class: App\Admin\QuestionAdmin
        arguments: [~ , App\Entity\Question , ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.question.title, show_in_dashboard: true }
        public: true
