vich_uploader:
    db_driver: orm

    mappings:
        baseConfigImageFon:
            uri_prefix: /images/baseConfigImageFon
            upload_destination: '%kernel.project_dir%/public/images/baseConfigImageFon'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        baseConfigImageLogo:
            uri_prefix: /images/baseConfigImageLogo
            upload_destination: '%kernel.project_dir%/public/images/baseConfigImageLogo'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        baseImageSlider:
            uri_prefix: /images/baseImageSlider
            upload_destination: '%kernel.project_dir%/public/images/baseImageSlider'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        basePhoneImageLogo:
            uri_prefix: /images/basePhoneImageLogo
            upload_destination: '%kernel.project_dir%/public/images/basePhoneImageLogo'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        baseSocialImage:
            uri_prefix: /images/baseSocialImage
            upload_destination: '%kernel.project_dir%/public/images/baseSocialImage'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        basePartnersImage:
            uri_prefix: /images/basePartnersImage
            upload_destination: '%kernel.project_dir%/public/images/basePartnersImage'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        testImage:
            uri_prefix: /images/testImage
            upload_destination: '%kernel.project_dir%/public/images/testImage'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        categoryImage:
            uri_prefix: /images/categoryImage
            upload_destination: '%kernel.project_dir%/public/images/categoryImage'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        categoryImageFon:
            uri_prefix: /images/categoryImageFon
            upload_destination: '%kernel.project_dir%/public/images/categoryImageFon'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        stock:
            uri_prefix: /images/stock
            upload_destination: '%kernel.project_dir%/public/images/stock'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

